[[questions]]
id = "97781ca8-ad58-449c-9769-e20b9d2e42a6"
type = "MultipleChoice"
prompt.prompt = """
Say you have a variable `v` of type `&mut Vec<i32>`, and you want to call the `len` method with the
following signature:

```
impl<T> Vec<T> {
  fn len(&self) -> usize {
    /* ... */
  }
}
```

If you try to compile the expression `v.len()`, which of the following statements best describes what happens?
"""
answer.answer = "It compiles, because the `&mut` reference is implicitly reborrowed as an `&` reference"
prompt.distractors = [
  "It does not compile, because `&mut Vec<i32>` is not the same type as `&Vec<i32>`",
  "It does not compile, `v` is not explicitly dereferenced",
  "It compiles, because `&self` can take any kind of reference"
]
context = """
The expression `v.len()` desugars to `Vec::len(&*v)`, which is a valid re-borrow of `v`, so this expression compiles.
You cannot, however, pass `v` directly to `Vec::len`, since `&self` specifically refers to immutable references.
"""

[[questions]]
id = "35a75881-eb08-486c-92b3-413ab512138a"
type = "MultipleChoice"
prompt.prompt = """
Consider these two methods that increment a field of a struct. Which style would be more idiomatic for Rust?

```
struct Point(i32, i32);
impl Point {
  fn incr_v1(mut self)  { self.0 += 1; }
  fn incr_v2(&mut self) { self.0 += 1; }
}
```
"""
answer.answer = "`incr_v2`"
prompt.distractors = [
  "`incr_v1`",
  "Both are idiomatic",
  "Neither are idiomatic"
]
prompt.answerIndex = 1
context = """
The `incr_v1` method is not idiomatic, because it consumes ownership of the `Point`. This means after calling `p.incr_v1()`, `p` 
would be unusable, which is probably not intended for this method.
"""

[[questions]]
id = "03a0a1ec-8ce6-40f2-b8b7-6dd5402aeb7d"
type = "Tracing"
prompt.program = """
struct Point(i32, i32);
impl Point {
  fn incr_x(&mut self) {
    self.0 += 1;
  }
}

fn main() {
  let mut p = Point(0, 0);
  p.incr_x();
  println!("{}", p.0);
}
"""
answer.doesCompile = true
answer.stdout = "1"
context = """ 
Remember that `.0` is valid for tuple structs like `Point`.
"""

[[questions]]
id = "be7be598-8a31-4c1a-9171-4ff90f512430"
type = "Tracing"
prompt.program = """
struct Point {
  x: i32,
  y: i32
}

impl Point {
  fn get_x(&mut self) -> &mut i32 {
    &mut self.x
  }
}

fn main() {
  let mut p = Point { x: 1, y: 2 };
  let x = p.get_x();
  *x += 1;
  println!("{} {}", *x, p.y);
}
"""
answer.doesCompile = false
answer.lineNumber = 16
context = """ 
Because `get_x` mutably borrows all of `p`, a program cannot use `p` in any way until `x` is no longer used. 
Therefore reading `x` and `p.y` in the same line is an ownership error.
"""